# Execution
# ansible-playbook mount.yml

- name: Test mount and unmounts
  hosts: all
  
  tasks:
  - name: Mount
    mount:
        path: /mnt
        src: cohesity-corp1:/ansible
        opts: bind
        fstype: none
        state: mounted
