# Execution
# ansible-playbook mount.yml

- name: Test mount and unmounts
  hosts: localhost
  remote_user: root

  tasks:
  - name: Mount
    mount:
        path: /mnt/ansible
        src: "cohesity-corp1:/ansible"
        opts: bind
        fstype: none
        state: mounted
