# Execution
# ansible-playbook mount.yml

- name: Test mount and unmounts
  hosts: all
  
  tasks:
  - name: Mount
    mount:
        fstype: nfs
        path: /tsdeploy
        src: cohesity-corp1:/ansible
        state: mounted
