# Execution
# ansible-playbook mount.yml

- name: Test mount and unmounts
  hosts: all
  become: yes
  
  tasks:
    - name: Create a directory if it does not exist
      file:
        path: /tsdeploy
        state: directory
        mode: '0755'
      become: yes
    
    -  name: Create a directory if it does not exist
       file:
         path: /home/oracle/to_depl/
         state: directory
         mode: '0755'
       become: yes
    
    - name: Mount
      mount:
        fstype: nfs
        path: /tsdeploy
        src: cohesity-corp1:/ansible
        state: mounted
        
    - name: copy the ear file - need to change this to just execute a move command from the mount
      command: mv /tsdeploy/testfile.txt /home/oracle/to_depl
