# Execution
# ansible-playbook mount.yml

- name: Test mount and unmounts
  hosts: all
  
  tasks:
  - name: Create a directory if it does not exist
  file:
    path: /tsdeploy
    state: directory
    mode: '0755'
	- name: Create a directory if it does not exist
  file:
    path: /home/oracle/to_depl/
    state: directory
    mode: '0755'
  - name: Mount
    mount:
        fstype: nfs
        path: /mnt
        src: cohesity-corp1:/ansible
        state: mounted
  - name: copy the ear file
    template:
      src: /tsdeploy/testfile.txt
      dest: /home/oracle/to_depl/
